### ISSUE TITLE
Can not Process Umlauts

### ISSUE THREAD

**Issue by garyee** [Tiggerito/WebSiteAdvantage.KeePass.Firefox#1]
Hi,

neat tool! :)
I ran into a fault while importing firefox xml:

```
Message: Import Failed
Program: Importer Xml
Version: 2.22
Assembly Version: 2.23.0.21106
Processor: 64bit
Processor Architecture: MSIL

Exception
Failed to load the password file. 
This may be due to the presence of foreign characters in the data. 
Please check the website for help

Invalid character in the given encoding. Line 133, position 41.
Source: WebSiteAdvantageKeePassFirefoxImporter
   at WebSiteAdvantageKeePassFirefoxImporter.FirefoxFormatImporterXml.Import(PwDatabase         pwStorage, Stream sInput, IStatusLogger slLogger)

Inner Exception
Invalid character in the given encoding. Line 133, position 41.
Source: System.Xml
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.InvalidCharRecovery(Int32& bytesCount, Int32& charsCount)
   at System.Xml.XmlTextReaderImpl.GetChars(Int32 maxCharsCount)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar,         NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at WebSiteAdvantageKeePassFirefoxImporter.FirefoxFormatImporterXml.Import(PwDatabase     pwStorage, Stream sInput, IStatusLogger slLogger)
```

It was an "ü" in a username.

**Comment by Tiggerito** [comment]
Thanks Gerald,

Firefox does not export some special characters correctly, so it can break the import process. 

The only solution I have is to edit the file and remove the special character, then fix it after the import.

Hope that helps.

## 

Tony

**Comment by garyee** [comment]
ah so I used the Importer from @fligtar like you proposed on your website ... maybe he can solve this.
But I took your advice and deleted the line form the xml. Btw. the ü was readable in Notepad++...

**Comment by Tiggerito** [comment]
The character can be read by text editors like notepad++ but it is encoded incorrectly for the XML file it is placed in. I would have to re-write the Microsoft XML parser I use from scratch to make it cope with poorly encoded files.

Unfortunately I don’t have the time to do that.

Maybe @fligtar can fix the encoding issue. I’m not sure if the exporter is supported anymore though.

## 

Tony

**Comment by fligtar** [comment]
I don't support Password Exporter anymore but you might be able to convince @jvillalobos to help update it.
